#!/usr/bin/env python3
"""gen-help-bend: build port/core/help.bend from the spec's verbatim help texts.

The help texts are long static strings. Their single source is the spec
appendix docs/spec-parts/HELP_TEXTS.md (clause S1.89): each text is a fenced
block preceded by `<!-- help-text: <key> -->`. This tool turns every block into
one Bend def (one string literal per line, concatenated once) and writes the
routing def `text(path, long)`. It reads the SPEC, never goldens/ and never
the original.

usage: gen-help-bend.py [--check]
  --check   build in memory and compare with the file on disk, write nothing
exit: 0 written (or up to date), 1 --check found a difference or a block is missing, 2 usage.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PART = ROOT / "docs" / "spec-parts" / "HELP_TEXTS.md"
OUT = ROOT / "port" / "core" / "help.bend"
BLOCK = re.compile(r"<!-- help-text: ([a-z.-]+) -->\n```text\n(.*?)```\n", re.S)
# key -> (def name, clause tag, what it is) for the six texts of 2026-09-20; every other key is derived: the level's
# words joined by `.`, `-short` for the `-h` form (`dep.add-short` is `br dep add -h`)
DEFS = {
    "top": ("top", "S1.29 S1.89", "`--help` and the `help` subcommand at the top level"),
    "list": ("list_long", "S1.29 S1.89", "`list --help`"),
    "list-short": ("list_short", "S1.29 S1.89", "`list -h`"),
    "dep": ("dep", "S1.25 S1.28 S1.89", "the `dep` group"),
    "label": ("label", "S1.26 S1.28 S1.89", "the `label` group"),
    "epic": ("epic", "S1.27 S1.28 S1.89", "the `epic` group"),
}


def level_of(key):
    """(the level's path as the parser names it, whether this is the -h form)"""
    short = key.endswith("-short")
    base = key[: -len("-short")] if short else key
    return ("" if base == "top" else base.replace(".", " "), short)


def derived(key):
    path, short = level_of(key)
    name = "h_" + (path or "top").replace(" ", "_").replace("-", "_") + ("_short" if short else "_long")
    what = f"`br {path} {'-h' if short else '--help'}`".replace("br  ", "br ")
    return (name, "S1.29 S1.89", what)
HEADER = '''# core/help — the help texts the port carries (S1.25–S1.29, S1.89).
# GENERATED by scripts/gen-help-bend.py from the spec appendix docs/spec-parts/HELP_TEXTS.md
# (clause S1.89): change the appendix and run the tool; do not edit the texts here.
# Every command level of the surface carries its `--help` and `-h` text; `text` answers "" for any other path.
# The texts are the original's bytes and keep its binary name `br` (DISC-006).
# Nothing here consults the original.
import Base
'''
def chain(pairs):
    """a Bool.pick chain over (path, def name); "" (a level the port does not carry) at the end"""
    expr = '""'
    for path, name in reversed(pairs):
        test = "String.is_empty(path)" if path == "" else f'String.eq(path, "{path}")'
        expr = f"Bool.pick(String, {test}, {name}(), {expr})"
    return expr


def router(defs):
    longs = [(level_of(k)[0], n) for k, (n, _, _) in defs.items() if not level_of(k)[1]]
    shorts = [(level_of(k)[0], n) for k, (n, _, _) in defs.items() if level_of(k)[1]]
    return f'''
# S1.29 S1.89 (spec twin) the `--help` text of a level; "" is a level whose help text the port does not carry
def text_long(+path: String) -> String:
  {chain(longs)}

# S1.29 S1.89 (spec twin) the `-h` text of a level
def text_short(+path: String) -> String:
  {chain(shorts)}

# S1.25 S1.29 S1.89 (spec twin) the help text of a level (`path` is "" at the top, else the words that lead to it);
# `long` is `--help`, the `help` subcommand or a bare group, as opposed to `-h`
def text(+path: String, long: Bool) -> String:
  match long:
    case True{{}}:
      text_long(path)
    case False{{}}:
      text_short(path)
'''


def literal(line):
    return '    "' + line.replace("\\", "\\\\").replace('"', '\\"') + '\\n" <>'


def build():
    blocks = dict(BLOCK.findall(PART.read_text()))
    missing = [key for key in DEFS if key not in blocks]
    if missing:
        raise SystemExit(f"gen-help-bend: no block for {missing} in {PART}")
    defs = dict(DEFS)
    for key in blocks:
        if key not in defs:
            defs[key] = derived(key)
    out = [HEADER]
    for key, (name, tag, what) in defs.items():
        body = blocks[key]
        if not body.endswith("\n"):
            raise SystemExit(f"gen-help-bend: block {key} does not end with a line feed")
        out.append(f"\n# {tag} (data) {what}, verbatim\ndef {name}() -> String:\n  String.concat(\n")
        out.append("\n".join(literal(line) for line in body[:-1].split("\n")))
        out.append("\n    Nil{})\n")
    out.append(router(defs))
    return "".join(out)


def main():
    args = sys.argv[1:]
    if args not in ([], ["--check"]):
        print(__doc__, file=sys.stderr)
        return 2
    text = build()
    if args:
        same = OUT.is_file() and OUT.read_text() == text
        print("gen-help-bend: up to date" if same else "gen-help-bend: port/core/help.bend differs from the spec")
        return 0 if same else 1
    OUT.write_text(text)
    print(f"gen-help-bend: wrote {OUT.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
