#!/usr/bin/env python3
"""gen-fixtures-bend: build port/fixtures.bend, the fixture texts the LAWS quote.

A closed law over a whole fixture needs the fixture's text as a Bend value. The
single source of those bytes is goldens/fixtures/<name>.jsonl (the original's
own output, never edited); this tool turns each named fixture into one Bend
def, one string literal per line, concatenated once. The generated file is
imported by port/LAWS.bend and port/PROOF.bend only, never by the program.

usage: gen-fixtures-bend.py [--check]
  --check   build in memory and compare with the file on disk, write nothing
exit: 0 written (or up to date), 1 --check found a difference or a fixture is missing, 2 usage.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "port" / "fixtures.bend"
FIXTURES = ["basic", "precision"]
HEADER = '''# fixtures — the texts of goldens/fixtures/*.jsonl as Bend values, for the laws ONLY.
# GENERATED by scripts/gen-fixtures-bend.py: change nothing here; a fixture is never edited
# (AGENTS.md "Fixtures are never overwritten"). The program never imports this file.
import Base
'''


def literal(line):
    escaped = line.replace("\\", "\\\\").replace('"', '\\"')
    return f'    "{escaped}\\n" <>'


def build():
    out = [HEADER]
    for name in FIXTURES:
        path = ROOT / "goldens" / "fixtures" / f"{name}.jsonl"
        if not path.is_file():
            raise SystemExit(f"gen-fixtures-bend: no fixture {path}")
        text = path.read_text()
        if not text.endswith("\n"):
            raise SystemExit(f"gen-fixtures-bend: fixture {name} does not end with a line feed")
        out.append(f"\n# S2.24 (data) the text of goldens/fixtures/{name}.jsonl, byte for byte\ndef {name}() -> String:\n  String.concat(\n")
        out.append("\n".join(literal(line) for line in text[:-1].split("\n")))
        out.append("\n    Nil{})\n")
    return "".join(out)


def main():
    args = sys.argv[1:]
    if args not in ([], ["--check"]):
        print(__doc__, file=sys.stderr)
        return 2
    text = build()
    if args:
        same = OUT.is_file() and OUT.read_text() == text
        print("gen-fixtures-bend: up to date" if same else "gen-fixtures-bend: port/fixtures.bend differs from goldens/fixtures")
        return 0 if same else 1
    OUT.write_text(text)
    print(f"gen-fixtures-bend: wrote {OUT.relative_to(ROOT)} ({len(text)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
